### ISSUE TITLE
Question on withdrawl amount

### ISSUE THREAD

**Issue by coulterj** [brndnmtthws/optimal-buy-gdax#14]
I have a question on the withdrawal amount.  I am sticking to the default of $25.  Ether seems to have done fine, but for BTC, it didn't want to transfer.  It has $68.84 USD worth of BTC, Shouldn't it have transferred?

--
Jun 10 00:42:20 docker[13572]: fiat_balances={'BTC': 68.8452891525, 'USD': 0.0585899719, 'ETH': 31.6041170672}
Jun 10 00:42:20 docker[13572]: only 0.0585899719 USD fiat balance remaining, withdrawing coins without buying
Jun 10 00:42:20 docker[13572]: BTC balance only 0.0094354500000000, not withdrawing
Jun 10 00:42:20 docker[13572]: withdrawing 0.05522878 ETH to EtherAddress

**Comment by brndnmtthws** [comment]
It's refusing to withdraw because you're below the minimum withdrawal amount for BTC (0.01 I believe). The limits are set by Coinbase/GDAX, and aren't configurable for an end user AFAIK.
