### ISSUE TITLE
Bitcoin Cash

### ISSUE THREAD

**Issue by AOEUPL-PHE** [brndnmtthws/optimal-buy-gdax#3]
Coinbase just added BCH.  is this all I need to start buying it?

```
coins = {
    'BTC': 'Bitcoin',
    'ETH': 'Ethereum',
    'LTC': 'Litecoin',
    'BCH': 'Bitcoin Cash',
}

minimum_order_size = {
    'BTC': 0.0001,
    'ETH': 0.001,
    'LTC': 0.01,
    'BCH': 0.0001,
}
```

https://blog.coinbase.com/buy-sell-send-and-receive-bitcoin-cash-on-coinbase-65f1b2c7214b

**Comment by brndnmtthws** [comment]
That should work, however at the time of writing GDAX is no longer trading bcash.

I'm not going to add it into my project because I feel that bcash is a hostile fork attempting to co-opt the Bitcoin name, but feel free to fork this repo and make it your own.

**Comment by sadam0930** [comment]
Someone's been spending too much time /r/Bitcoin

**Comment by brndnmtthws** [comment]
Have a look at #4. I didn't test it yet, but it should allow you to apply this to whatever you want on GDAX. The GDAX sandbox is currently busted, so I can't test it, but when I do I'll merge the PR.

**Comment by AOEUPL-PHE** [comment]
just browsed the code, looks good.  also afraid to try.  i think i share your thoughts on bch, but there are rumors that they will be adding xrp and others, so this will probably be useful even if you aren't a bch fan.  😄
