### ISSUE TITLE
Trouble with copying files over

### ISSUE THREAD

**Issue by KentonPrescott** [brndnmtthws/optimal-buy-gdax#5]
Hello,

I am having trouble with transferring files to the virtual instance (hosted through Digital Ocean). 
While connected to the remote host via ssh I execute this line: `sudo cp optimal-buy-gdax-*.{service,timer} /etc/systemd/system`

And I receive this error:
`cp: cannot stat 'optimal-buy-gdax-*.timer': No such file or directory`

While still connected to the remote host, I then tried to use SCP: `scp /directory/optimal-buy-gdax-master/optimal-buy-gdax-.*{service,timer} /etc/systemd/system`

But received this error:
`cp: cannot stat '/directory/optimal-buy-gdax-master/optimal-buy-gdax-.*service': No such file or directory`

I am still unfamiliar with remote machines, so excuse me for the noob question!

Thanks!

**Comment by brndnmtthws** [comment]
I need to grab a copy of the source code (which perhaps isn't clear from the instructions). You have 2 options: you can either clone the repo with Git, or you can download a copy of the entire repo from https://github.com/brndnmtthws/optimal-buy-gdax/archive/master.zip.

**Comment by KentonPrescott** [comment]
Thanks for your prompt response!
With the cloned/copied repo on my local machine, I still recieve the same error messages.

I'll look into other transfer methods, but just so I get this right, please correct me if we need anything other than the following files on the remote machine:
- optimal-buy-gdax-deposit.timer
- optimal-buy-gdax-deposit-service.app
- optimal-buy-gdax-buy.timer
- optimal-buy-gdax-buy.service.app

**Comment by brndnmtthws** [comment]
Those 4 files are just the systemd units, so yes that's all you really need to configure and run everything. Keep in mind that you're running a Docker container, which is basically arbitrary software that you're also pulling down from the internet when you run it.
